---
parameters:
    assimtech_fiat.accountant.class: Assimtech\Fiat\Accountant


services:
    assimtech_fiat.accountant:
        class: "%assimtech_fiat.accountant.class%"
    Assimtech\Fiat\Accountant: '@assimtech_fiat.accountant'

    assimtech_fiat.twig.accountant:
        class: Assimtech\Fiat\Twig\Extension\Accountant
        arguments:
            - "@assimtech_fiat.accountant"
        tags:
            - { name: twig.extension }
    Assimtech\Fiat\Twig\Extension\Accountant: '@assimtech_fiat.twig.accountant'
